---
- name: Set profiler
  hosts: 
  - midtier
  - bucket
  tags: 
  - set_profiler_hosts
  tasks:
  - name: Set profiler Hosts
    shell: cd /users/cseas002/HDSearch-Multinode/profiler; ./setHosts.sh 1 $(hostname | awk -F"." '{print $1}' | sed 's/node//g') $(hostname | awk -F"." '{print $1}' | sed 's/node//g')
    async: 10000 
    poll: 0
- name: Run remote profiler
  hosts: client
  tags: 
  - run_profiler
  tasks:
  - name: Run remote profiler
    shell: /users/cseas002/HDSearch-Multinode/scripts/startProfiler.sh {{ HOST_FILE }} {{ ITERATION }}
- name: Kill remote profiler
  hosts: 
  - bucket
  - midtier
  tags: 
  - kill_profiler
  tasks:
  - name: Kill remote profiler       
    ignore_errors: yes
    shell: cd /users/cseas002/HDSearch-Multinode/profiler; sudo ./profiler.sh kill_profiler

  - name: Run remote socwatch  
  hosts: 
  - bucket
  - midtier  
  tags:   
  - run_socwatch  
  tasks:  
  - name: Run remote socwatch    
    command: sudo /opt/intel/oneapi/vtune/2023.2.0/socwatch/x64/socwatch -s 60 -t {{ MONITOR_TIME }} -f cpu-cstate -m -r int -o {{ OUTPUT_FILE }}    
    async: 10000     
    poll: 0 
 